apiVersion: v1
kind: Service
metadata:
  name: app1
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: app1-service_mapping
      host: app1.your-domain
      prefix: /
      service: app1:80
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: app1
    
    
    
