apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- service.yaml
images:
- name: chiper
  newName: ghcr.io/diegocarlo0526/testargocd/nginx
  newTag: "28"
- name: ghcr.io/diegocarlo0526/testargocd/nginx
  newTag: "30"
- name: nginx
  newName: ghcr.io/diegocarlo0526/testargocd/nginx
  newTag: "29"
