apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- deploy.yaml
- service.yaml
#- virtual.yaml
#- gatewat.yaml
images:
- name: ghcr.io/diegocarlo0526/testargocd/nginx
  newTag: "31"
