apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: segundo
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - beta-gateway
  http:
    - match:
        - uri:
            prefix: /segundo/
      rewrite:
        uri: /
      route:
        - destination:
            host: nginx.default.svc.cluster.local
            port:
              number: 80
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - "*"
        allowCredentials: true
        allowHeaders:
          - "*"