apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: segundo
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - bookinfo-gateway
  http:
    - match:
        - uri:
            prefix: /argocd/
      rewrite:
        uri: /
      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80