apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
  namespace: argocd
spec:
  hosts:
    - "argocd.ecositema.com"
  gateways:
    - argocd-gateway
  http:
  - route:
      - destination:
          host: argocd-server.argocd.svc.cluster.local
          port:
            number: 80