# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: test-selfsigned
#   namespace: istio-system
# spec:
#   selfSigned: {}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging
spec:
 acme:
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   email: admin@ecosistema.com
   privateKeySecretRef:
     name: letsencrypt-staging
   solvers:
   - http01:
       ingress:
         name:  istio-ingress
---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: selfsigned-cert
#   namespace: istio-system
# spec:
#   dnsNames:
#     - ecositema.com
#     - kiali.ecositema.com
#     - argocd.ecositema.com
#   secretName: selfsigned-cert-tls
#   issuerRef:
#     name: letsencrypt-staging