apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: istio-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: istio-system
spec:
  dnsNames:
    - ecositema.com
    - kiali.ecositema.com
    - argocd.ecositema.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned