apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  hosts:
    - "kiali.ecositema.com"
  gateways:
    - istio-gateway
  http:
  - route:
      - destination:
          host: kiali.istio-system.svc.cluster.local
          port:
            number: 20001