apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - 'kiali.ecositema.com'
        - 'grafana.ecositema.com'
        - 'api.ecositema.com'
---        
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - 'api.ecositema.com'
      listeners:
      - name: http
        address:
          socketAddress:
            port: 80
            ip: 0.0.0.0
        http:
          useRemoteAddress: true        
