apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - 'kiali.ecositema.com'
    # - port:
    #     name: https-443
    #     number: 443
    #     protocol: HTTPS
    #   hosts:
    #     - 'kiali.ecositema.com'
    #   tls:
    #     mode: SIMPLE  