apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.137.61
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: app2