apiVersion: v1
kind: Service
metadata:
  name: app3
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: app3-service_mapping
      host: app3.your-domain
      prefix: /
      service: app3:80
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: app3